-- BigQuery table schema derived from metadata_json structure
-- Replace PROJECT_ID with your GCP project ID if needed.
--
-- metadata_json 필드 → BigQuery 컬럼 매핑:
-- - case_id → case_id
-- - filename → case_number
-- - case_type → case_type
-- - fault_type → fault_type
-- - alimony_final_amount → alimony_amount (INT64)
-- - alimony_reason → alimony_reason
-- - property_ratio_plaintiff → property_ratio_plaintiff (FLOAT64)
-- - marriage_duration_years → marriage_duration_years (INT64)
-- - key_summary → summary
-- - has_children → has_children (BOOL)
-- - (generated by embedding) → full_text_embedding

CREATE TABLE `pio-test-36cf5.divorce_analytics.precedent_cases` (
  case_id STRING,                                  -- metadata_json.case_id
  case_number STRING,                              -- metadata_json.filename
  case_type STRING,                                -- metadata_json.case_type
  alimony_amount INT64,                            -- metadata_json.alimony_final_amount
  alimony_reason STRING,                           -- metadata_json.alimony_reason
  property_ratio_plaintiff FLOAT64,                -- metadata_json.property_ratio_plaintiff
  marriage_duration_years INT64,                   -- metadata_json.marriage_duration_years
  fault_type STRING,                               -- metadata_json.fault_type
  summary STRING,                                  -- metadata_json.key_summary
  has_children BOOL,                               -- metadata_json.has_children (true/false/null)
  full_text_embedding ARRAY<FLOAT64>              -- generated from key_summary + alimony_reason + fault_type
)
CLUSTER BY fault_type;
